### ISSUE TITLE
Looking forward to see the tensorflow version

### ISSUE THREAD

**Issue by henryace** [lukasruff/Deep-SVDD#2]
Hi author,

Are you still planning to release the tensorflow version?
I'm looking forward to see it.

Thank you!

**Comment by lukasruff** [comment]
Hi henryace,

yes, we plan to either release a tensorflow or PyTorch version of Deep SVDD in the future.

Thanks!
Lukas

**Comment by wanglijie95** [comment]
Hi, lukasruff,

Is there a tensorflow version now ? I am also looking forward to it.

Thanks!
