### ISSUE TITLE
Training and testing on custom data?

### ISSUE THREAD

**Issue by bnsblue** [lukasruff/Deep-SVDD#3]
Thanks for the great work! May I ask if you can provide any guidelines or tutorials on how to use Deep SVDD on custom image datasets?

Any suggestion is highly appreciated!

**Comment by lukasruff** [comment]
Thanks for the kind words.

To use Deep SVDD on your custom image datasets, you would have to write a DataLoader sub-class that specifies how the data can be loaded and should be pre-processed (.load_data method). Moreover, you must specify a neural network architecture you would like to apply for your data (. build_architecture method and .build_autoencoder method if you would like to pretrain via autoencoder, which I recommend).

Have a look at mnist.py and cifar10.py in the src/datasets directory to see how this is implemented for MNIST and CIFAR-10.

Also, I will release a cleaner and simpler PyTorch implementation of the method soon for which it will be easier to use implement your own datasets.

**Comment by pavanvyn** [comment]
Hello, I am using your code for my dataset. I have a few queries -

1) My training data is labelled while my testing data is not. How should I go about implementing your code? What changes should I make?
2) Regarding the data loader, I am confused about the syntax. Do I load my data through a .csv file or provide a path to my image directories? I have been unable to find decent methods to implement the data loading.
3) For my case, do I have to edit the base directory modules in any way? I realize that I don't have to edit the optim and the util modules.

Thank you.
