### ISSUE TITLE
STOP sign dataset

### ISSUE THREAD

**Issue by PramuPerera** [lukasruff/Deep-SVDD#6]
Hello,

I would like to compare with your method in the gtsrb STOP sign database. Could you please direct me to the exact version you tested in your paper? Thanks.

Pram

**Comment by lukasruff** [comment]
Hi Pramuditha,

I've send you an e-mail with a link to the adversarial attacks we generated for the ICML paper experiment.

Cheers,
Lukas

**Comment by chunyuner** [comment]
Hi Pramuditha,
I'm curious about the method of generating STOP adversarial attacks.Do you use the foolbox or other tools?Could you please direct me to the exact version you or author tested in experiment? Thank you very much.
chunyun

**Comment by PramuPerera** [comment]
Hello,

I have used this dataset for experiments in a unpublished work. I obtained it from Lukas. Thanks.

Best,
Pramuditha
________________________________
